### ISSUE TITLE
[info] [chore] Line Height | request for clarification | More Content on Line Height and related

### ISSUE THREAD

**Issue by nikhilkuyya** [FrontendMasters/bootcamp#66]
I see that line height is confusing to me comparing to reading done on other sources.

- [Our Source of Line Height](https://github.com/FrontendMasters/bootcamp/blob/master/lessons/css.md#line-height)
- [MDN Line Height](https://developer.mozilla.org/en-US/docs/Web/CSS/line-height)
- [BLog Source](https://iamvdo.me/en/blog/css-font-metrics-line-height-and-vertical-align)

I see line height helps us to set the line box height and distance between is line is main usage with line height.

**Comment by jen4web** [comment]
Line height should have no units. It is a proportion. If the user makes the text size larger, the line height will not scale if units are declared. This means the text will overlap at larger sizes. A good default is line-height: 1.5; Hope that helps?

**Comment by nikhilkuyya** [comment]
Line Height is the height of line right. but i see the line height is said to increase the distance between the lines.
According to my reading, creating the distance b/w the line is the use case(application). 
but line height is to specify the height of line.
the distinction missing or may be i am not correct.
may be i would like to know that distinction in that side and views.

**Comment by jen4web** [comment]
The typography definition of line height may not be the same as the web definition of line height. Increasing the distance between lines (as in a paragraph or a list) is the primary use of this property. I wouldn't overthink it too much or try to fit it with classical typography.

**Comment by nikhilkuyya** [comment]
Thank you !! :)
